@myhost = http://localhost:3000

GET {{myhost}}/events

###
# @name createEvent
POST {{myhost}}/events
Content-Type: application/json

{
  "name": "New Event",
  "description": "This is a new event",
  "date": "2024-01-01T00:00:00",
  "price": 100
}
###

@eventId = {{ createEvent.response.body.id }}

###
GET {{myhost}}/events/{{eventId}}

###
PATCH {{myhost}}/events/{{eventId}}
Content-Type: application/json

{
  "name": "New Event",
  "description": "This is a new event",
  "date": "2024-01-01T00:00:00",
  "price": 100
}

###
DELETE {{myhost}}/events/{{ eventId }}

###
GET {{myhost}}/events/{{eventId}}/spots

###
# @name createSpot
POST {{myhost}}/events/{{eventId}}/spots
Content-Type: application/json

{
  "name": "A3"
}

###
@spotName = {{ createSpot.response.body.name }}

###
POST http://localhost:3000/events/{{eventId}}/reserve
Content-Type: application/json

{
  "spots": ["{{ spotName }}"],
  "ticket_kind": "full",
  "email": "test@test.com"
}